data:
  type: cell
  source: non-targeting
  target: IFNGR2
  condition: target_gene

dataloader:
  batch_size: 256
  shuffle: true

datasplit:
  groupby: target_gene
  name: toggle_ood
  test_size: 0.2
  random_state: 0